version: '2'
services:
  wallet:
    build:
      context: .
      dockerfile: Dockerfile-test
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - "mongo:mongo"
    environment:
      MONGODB_URI: "mongodb://mongo/school-wallet"
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
