version: '2'
services:
  wallet:
    image: "node-school-app"
    ports:
      - "80:3000"
    depends_on:
      - mongo
    links:
      - "mongo:mongo"
    environment:
      MONGODB_URI: "mongodb://mongo/school-wallet"
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - "/ci/db:/data/db"
